# Generated by Django 5.1.7 on 2025-03-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('BloodGroup', models.CharField(max_length=3)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
